# Dockerfile.frontend
FROM golang:1.25-alpine AS builder

WORKDIR /app

# Копируем go.mod
COPY go.mod go.sum ./
RUN go mod download

# Копируем весь проект
COPY . .

# Собираем фронтенд
RUN CGO_ENABLED=0 GOOS=linux go build -gcflags="all=-N -l" -o frontend ./cmd/frontend/main.go

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/

# Копируем бинарник и web
COPY --from=builder /app/frontend .
COPY --from=builder /app/web ./web

EXPOSE 3001
CMD ["./frontend"]