# Dockerfile.admin
FROM golang:1.25-alpine AS builder

WORKDIR /app

# Копируем go.mod
COPY go.mod go.sum ./
RUN go mod download

# Копируем весь проект
COPY . .


# Собираем админ с отладочной информацией
RUN CGO_ENABLED=0 GOOS=linux go build -gcflags "all=-N -l" -o admin ./cmd/admin/main.go

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/

# Копируем бинарник, web и dlv
COPY --from=builder /app/admin .
COPY --from=builder /app/web ./web

EXPOSE 3002
CMD ["./admin"]